### ISSUE TITLE
Dotfiler not portable across Ubuntu Bash on Windows

### ISSUE THREAD

**Issue by cybtachyon** [svetlyak40wt/dotfiler#20]
When running `dot update`, it does not properly recognize and handle existing symlinks when inside a symlinked home directory on Ubuntu Bash on Windows.

```bash
dreese@samhost:~$ dot update
CANT LINK: /home/testuser/.bash_profile -> /mnt/c/Users/testuser/.dotfiles/base/.bash_profile
Traceback (most recent call last):
  File "/home/testuser/.dotfiles/bin/dot", line 43, in <module>
    arguments)
  File "/mnt/f/Users/testuser/.dotfiles/bin/lib/dot/core.py", line 441, in update
    created_links = processor(remove_actions + actions, created_links, fs)
  File "/mnt/f/Users/testuser/.dotfiles/bin/lib/dot/core.py", line 77, in processor_real
    mapping[action[0].replace('-', '_')](*action[1:])
  File "/mnt/f/Users/testuser/.dotfiles/bin/lib/dot/core.py", line 63, in link
    fs.symlink(source, target)
  File "/mnt/f/Users/testuser/.dotfiles/bin/lib/dot/real_filesystem.py", line 28, in symlink
    os_symlink(source, link_name)
OSError: [Errno 17] File exists
```

**Comment by svetlyak40wt** [comment]
OMG, ubuntu bash on windows? What is this beast?

**Comment by svetlyak40wt** [comment]
Anyway, I don't have a Windows. Feel free to fix the issue.

**Comment by cybtachyon** [comment]
This is potentially resolved by the introduction of WSL2. I will close this issue if it is resolved after testing.

**Comment by fniessen** [comment]
FYI, I'm using dotfiler for a couple of days, on Windows, with WSL1. And it works just fine.
