### ISSUE TITLE
Not Python3 compatible

### ISSUE THREAD

**Issue by lxsli** [svetlyak40wt/dotfiler#23]
```Traceback (most recent call last):
  File "bin/dot", line 31, in <module>
    from dot import COMMANDS
  File "/home/alee/.dotfiles/bin/lib/dot/__init__.py", line 2, in <module>
    from .core import COMMANDS
  File "/home/alee/.dotfiles/bin/lib/dot/core.py", line 486
    print env
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(env)?
```

I see you just changed the shebang from `python2` to `python`, so I won't propose changing that back. Maybe you could `import print_function from __future__`; or simply move to Py3 as Py2 will be EOL soon anyway?

**Comment by svetlyak40wt** [comment]
Feel free to make a pull-request. Probably, a separate branch for python3 could be used to not support both pythons simultaneously.
